name: sync to gitee

on:
    push:
        branches:
            - 'main' # 只针对 dev 分支
        paths:
            - '**'

jobs:
    sync-to-gitee:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: set ssh key # 临时设置 ssh key
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{secrets.SYNC_GITEE_SSH}}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan "121.5.224.48" >> ~/.ssh/known_hosts
            - name: sync to gitee # 同步
              run: |
                  git remote add gitee git@gitee.com:flyrj/dai.git
                  git push gitee main:master
            - name: delete ssh key # 删除 ssh key
              run: rm -rf ~/.ssh/id_rsa